[book]
title = "Rust in Pieces"
authors = ["prrao87", "sanders41"]
language = "en"
src = "src"

[output.html]
site-url = "/rustinpieces/"
additional-css = ["theme/extra.css"]
git-repository-url = "https://github.com/thedataquarry/rustinpieces"
edit-url-template = "https://github.com/thedataquarry/rustinpieces/edit/main/book/{path}"

[output.html.fold]
enable = true
level = 1  # Avoid showing subsections in the sidebar as it becomes overwhelming
